default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: admin
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rubycon_dev

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
